### ISSUE TITLE
ble.Connect Mac OS X Mogave

### ISSUE THREAD

**Issue by benji-bou** [go-ble/ble#32]
Hi, 

# Problem
Does someone try to connect to a peripheral using 
``` ble.Connect(ctx context.Context, f AdvFilter) (Client, error)```
on Mogave (beta 10.14) 
 On my side the AdvFilter is never called. 

# Test Environement 
On High Sierra the AdvFilter is called correctly and I'm able to filter peripherals and connect to the choosen one.
On Mogave AdvFilter is never called. then timeout based on context provided

Both environment are the same (except for OS Version).
- go 1.11 darwin/amd64
- Same BLE Device to connect to
- Same room (same RF Interferences)

Best

**Comment by deadprogram** [comment]
We should look at https://github.com/Timeular/noble-mac which seems to have addressed the changes in Mojave...

**Comment by sacabuche** [comment]
@deadprogram Hi there, may be in the mean time I can find the xpc codes if you give me a hint in how to get them. And then we can move to a beter solution, like the one of noble-mac

**Comment by deadprogram** [comment]
I spent some time a few weeks back trying to hack my way around the xpc messages changes, but was not successful. There are new additional messages, some messages have changes, etc. 

I was able to get a connection, but trying to enumerate the services was just not happening for me. This is where I came to the conclusion that the native approach is the only way forward at this point that will justify the time investment required.

Anyhow, I did not find time to work on it further myself. Since I do not do much macOS coding these days, it will be very time-consuming for me to do the needed changes, but I would pair or help out gladly.

**Comment by sacabuche** [comment]
@deadprogram Thank you! Then I will look in the native approach. May be making a swift wrapper library and read it from golang C.

**Comment by deadprogram** [comment]
I'm not sure, but I do not think you can compile the swift code from within the CGo. The .mm files used by noble-mac are macOS C++ files so I *think* that we will need that, plus C wrappers to be called by CGo.

**Comment by deadprogram** [comment]
To elaborate a little on what I thinks needs to be done...

IMO we need to replace the macOS implementation here https://github.com/go-ble/ble/tree/master/darwin

With code more like this:
https://github.com/Timeular/noble-mac/tree/master/src

For example...

The place to start is with a new implementation of the go-ble Device interface for darwin:
https://github.com/go-ble/ble/blob/master/device.go#L6-L45

The implementation of this needs to use code like
https://github.com/Timeular/noble-mac/blob/master/src/ble_manager.mm#L93-L108

As you can see, it is not just a 1to1 translation of code, but the underlying task being performed is the same, and the BLE API itself is the same. Someone with more up to date ObjC++ knowledge than I have would not have a difficult time, probably. :)

**Comment by estutzenberger** [comment]
Unfortunately, I am not able to maintain the OS X side of this repository. If someone is willing to be a maintainer for it and implement the suggested changes, I'm all for that!
